compute_environment: LOCAL_MACHINE
debug: false
distributed_type: DEEPSPEED

num_machines: 1
num_processes: 8
machine_rank: 0
main_process_ip: localhost
# main_process_port: 35681

downcast_bf16: "no"
# mixed_precision: bf16   # will be ignored when using deepseed cofnig

rdzv_backend: static
same_network: true
use_cpu: false
dynamo_backend: "inductor"
